export enum IconBtnNamesEnum {
  Left = 'left',
  Phone = 'phone',
  Plus = 'plus',
  Repeat = 'repeat',
  Right = 'right',
  Search = 'search',
  Setting = 'setting',
  Share = 'share',
  Users = 'users',
  Close = 'close',
  RadioButton = 'radio-button',
  Apple = 'apple',
  Bell = 'bell',
  Burger = 'burger',
  Calendar = 'calendar',
  Camera = 'camera',
  Check = 'check',
  Copy = 'copy',
  Dots = 'dots',
  DotSmall = 'dots-small',
  Down = 'down',
  Edit = 'edit',
  Facebook = 'facebook',
  Home = 'home',
}
